//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class factoEntities : DbContext
    {
        public factoEntities()
            : base("name=factoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<empresa> empresa { get; set; }
    
        public virtual int proc_emp_delempnumid(string p_emp_numid)
        {
            var p_emp_numidParameter = p_emp_numid != null ?
                new ObjectParameter("p_emp_numid", p_emp_numid) :
                new ObjectParameter("p_emp_numid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_emp_delempnumid", p_emp_numidParameter);
        }
    
        public virtual int proc_emp_insemp(string p_emp_tipid, string p_emp_numid, string p_emp_nom, string p_emp_dir, string p_emp_ciu, string p_emp_depto, string p_emp_tel, string p_emp_tel2, string p_emp_tel3, string p_emp_email, string p_emp_web, string p_emp_rlegal, Nullable<System.DateTime> p_emp_fconstit, Nullable<System.DateTime> p_emp_fregistro)
        {
            var p_emp_tipidParameter = p_emp_tipid != null ?
                new ObjectParameter("p_emp_tipid", p_emp_tipid) :
                new ObjectParameter("p_emp_tipid", typeof(string));
    
            var p_emp_numidParameter = p_emp_numid != null ?
                new ObjectParameter("p_emp_numid", p_emp_numid) :
                new ObjectParameter("p_emp_numid", typeof(string));
    
            var p_emp_nomParameter = p_emp_nom != null ?
                new ObjectParameter("p_emp_nom", p_emp_nom) :
                new ObjectParameter("p_emp_nom", typeof(string));
    
            var p_emp_dirParameter = p_emp_dir != null ?
                new ObjectParameter("p_emp_dir", p_emp_dir) :
                new ObjectParameter("p_emp_dir", typeof(string));
    
            var p_emp_ciuParameter = p_emp_ciu != null ?
                new ObjectParameter("p_emp_ciu", p_emp_ciu) :
                new ObjectParameter("p_emp_ciu", typeof(string));
    
            var p_emp_deptoParameter = p_emp_depto != null ?
                new ObjectParameter("p_emp_depto", p_emp_depto) :
                new ObjectParameter("p_emp_depto", typeof(string));
    
            var p_emp_telParameter = p_emp_tel != null ?
                new ObjectParameter("p_emp_tel", p_emp_tel) :
                new ObjectParameter("p_emp_tel", typeof(string));
    
            var p_emp_tel2Parameter = p_emp_tel2 != null ?
                new ObjectParameter("p_emp_tel2", p_emp_tel2) :
                new ObjectParameter("p_emp_tel2", typeof(string));
    
            var p_emp_tel3Parameter = p_emp_tel3 != null ?
                new ObjectParameter("p_emp_tel3", p_emp_tel3) :
                new ObjectParameter("p_emp_tel3", typeof(string));
    
            var p_emp_emailParameter = p_emp_email != null ?
                new ObjectParameter("p_emp_email", p_emp_email) :
                new ObjectParameter("p_emp_email", typeof(string));
    
            var p_emp_webParameter = p_emp_web != null ?
                new ObjectParameter("p_emp_web", p_emp_web) :
                new ObjectParameter("p_emp_web", typeof(string));
    
            var p_emp_rlegalParameter = p_emp_rlegal != null ?
                new ObjectParameter("p_emp_rlegal", p_emp_rlegal) :
                new ObjectParameter("p_emp_rlegal", typeof(string));
    
            var p_emp_fconstitParameter = p_emp_fconstit.HasValue ?
                new ObjectParameter("p_emp_fconstit", p_emp_fconstit) :
                new ObjectParameter("p_emp_fconstit", typeof(System.DateTime));
    
            var p_emp_fregistroParameter = p_emp_fregistro.HasValue ?
                new ObjectParameter("p_emp_fregistro", p_emp_fregistro) :
                new ObjectParameter("p_emp_fregistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_emp_insemp", p_emp_tipidParameter, p_emp_numidParameter, p_emp_nomParameter, p_emp_dirParameter, p_emp_ciuParameter, p_emp_deptoParameter, p_emp_telParameter, p_emp_tel2Parameter, p_emp_tel3Parameter, p_emp_emailParameter, p_emp_webParameter, p_emp_rlegalParameter, p_emp_fconstitParameter, p_emp_fregistroParameter);
        }
    
        public virtual ObjectResult<proc_emp_selempnumid_Result> proc_emp_selempnumid(string p_emp_numid)
        {
            var p_emp_numidParameter = p_emp_numid != null ?
                new ObjectParameter("p_emp_numid", p_emp_numid) :
                new ObjectParameter("p_emp_numid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_emp_selempnumid_Result>("proc_emp_selempnumid", p_emp_numidParameter);
        }
    
        public virtual int proc_emp_updemp(string p_emp_tipid, string p_emp_numid, string p_emp_nom, string p_emp_dir, string p_emp_ciu, string p_emp_depto, string p_emp_tel, string p_emp_tel2, string p_emp_tel3, string p_emp_email, string p_emp_web, string p_emp_rlegal, Nullable<System.DateTime> p_emp_fconstit, Nullable<System.DateTime> p_emp_fregistro)
        {
            var p_emp_tipidParameter = p_emp_tipid != null ?
                new ObjectParameter("p_emp_tipid", p_emp_tipid) :
                new ObjectParameter("p_emp_tipid", typeof(string));
    
            var p_emp_numidParameter = p_emp_numid != null ?
                new ObjectParameter("p_emp_numid", p_emp_numid) :
                new ObjectParameter("p_emp_numid", typeof(string));
    
            var p_emp_nomParameter = p_emp_nom != null ?
                new ObjectParameter("p_emp_nom", p_emp_nom) :
                new ObjectParameter("p_emp_nom", typeof(string));
    
            var p_emp_dirParameter = p_emp_dir != null ?
                new ObjectParameter("p_emp_dir", p_emp_dir) :
                new ObjectParameter("p_emp_dir", typeof(string));
    
            var p_emp_ciuParameter = p_emp_ciu != null ?
                new ObjectParameter("p_emp_ciu", p_emp_ciu) :
                new ObjectParameter("p_emp_ciu", typeof(string));
    
            var p_emp_deptoParameter = p_emp_depto != null ?
                new ObjectParameter("p_emp_depto", p_emp_depto) :
                new ObjectParameter("p_emp_depto", typeof(string));
    
            var p_emp_telParameter = p_emp_tel != null ?
                new ObjectParameter("p_emp_tel", p_emp_tel) :
                new ObjectParameter("p_emp_tel", typeof(string));
    
            var p_emp_tel2Parameter = p_emp_tel2 != null ?
                new ObjectParameter("p_emp_tel2", p_emp_tel2) :
                new ObjectParameter("p_emp_tel2", typeof(string));
    
            var p_emp_tel3Parameter = p_emp_tel3 != null ?
                new ObjectParameter("p_emp_tel3", p_emp_tel3) :
                new ObjectParameter("p_emp_tel3", typeof(string));
    
            var p_emp_emailParameter = p_emp_email != null ?
                new ObjectParameter("p_emp_email", p_emp_email) :
                new ObjectParameter("p_emp_email", typeof(string));
    
            var p_emp_webParameter = p_emp_web != null ?
                new ObjectParameter("p_emp_web", p_emp_web) :
                new ObjectParameter("p_emp_web", typeof(string));
    
            var p_emp_rlegalParameter = p_emp_rlegal != null ?
                new ObjectParameter("p_emp_rlegal", p_emp_rlegal) :
                new ObjectParameter("p_emp_rlegal", typeof(string));
    
            var p_emp_fconstitParameter = p_emp_fconstit.HasValue ?
                new ObjectParameter("p_emp_fconstit", p_emp_fconstit) :
                new ObjectParameter("p_emp_fconstit", typeof(System.DateTime));
    
            var p_emp_fregistroParameter = p_emp_fregistro.HasValue ?
                new ObjectParameter("p_emp_fregistro", p_emp_fregistro) :
                new ObjectParameter("p_emp_fregistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_emp_updemp", p_emp_tipidParameter, p_emp_numidParameter, p_emp_nomParameter, p_emp_dirParameter, p_emp_ciuParameter, p_emp_deptoParameter, p_emp_telParameter, p_emp_tel2Parameter, p_emp_tel3Parameter, p_emp_emailParameter, p_emp_webParameter, p_emp_rlegalParameter, p_emp_fconstitParameter, p_emp_fregistroParameter);
        }
    }
}
